config/routes.rb
Mossutstallningar::Application.routes.draw do
  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'static_pages#start'

  get 'svt', to: 'static_pages#svt', as: 'svt'

  get 'cts', to: redirect('/sidor/inauguration-of-studio-mossutstallningar-closing-of-creative-time-summit-stockholm')

  localized do
    resources :projects, only: [:show]
    resources :pages, only: [:show]
    resources :products, only: [:index, :show]
    resources :takes, only: [:index, :show]

    get 'search', to: 'search#index', as: 'search'

    get 'closed', to: 'static_pages#closed', as: 'closed'
  end
end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
  belongs_to :attachable, polymorphic: true

  has_attached_file :attachment

  validates :name, presence: true
  validates_attachment_presence :attachment
  validates_attachment_content_type :attachment, content_type: ['application/zip', 'application/pdf', 'audio/mpeg', 'audio/x-mpeg', 'audio/mp3', 'audio/x-mp3', 'audio/mpeg3', 'audio/x-mpeg3', 'audio/mpg', 'audio/x-mpg', 'audio/x-mpegaudio']

  def url
    attachment.url
  end
end

app/models/concerns/pageable.rb
module Pageable
  extend ActiveSupport::Concern

  included do
    # friendly_id
    friendly_id :title, use: :slugged

    # validations
    validates :title, presence: true

    # scopes
    scope :published, -> { where(published: true) }

    # relations
    has_many :images, as: :imageable
    has_many :attachments, as: :attachable

    # nested attributes
    accepts_nested_attributes_for :images, allow_destroy: true
    accepts_nested_attributes_for :attachments, allow_destroy: true

    def featured_image
      images.first
    end

    protected

    def should_generate_new_friendly_id?
      slug.blank? || title_changed?
    end
  end
end

app/models/concerns/searchable.rb
module Searchable
  extend ActiveSupport::Concern

  included do
    include PgSearch

    pg_search_scope :search, against: {
      title: 'A',
      body: 'B'
    }
  end
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :imageable, polymorphic: true

  # http://www.imagemagick.org/script/command-line-processing.php#geometry
  has_attached_file :attachment, styles: {
    small:  '400x400>',
    large:  '1000x1000>'
  }

  validates :position, presence: true
  validates_attachment_presence :attachment
  validates_attachment_content_type :attachment, content_type: /\Aimage/

  scope :for_gallery, -> { where(for_gallery: true) }
  scope :order_by_position, -> { order(position: :desc) }

  def small
    attachment.url(:small)
  end

  def large
    attachment.url(:large)
  end
end

app/models/page.rb
class Page < ActiveRecord::Base
  extend FriendlyId
  include Searchable
  include Pageable

  belongs_to :page_category

  scope :order_by_position, -> { order(position: :asc, id: :desc) }
end

app/models/page_category.rb
class PageCategory < ActiveRecord::Base
  validates :name, presence: true

  has_many :pages
end

app/models/product.rb
class Product < ActiveRecord::Base
  extend FriendlyId
  include Searchable
  include Pageable
end

app/models/project.rb
class Project < ActiveRecord::Base
  extend FriendlyId
  include Searchable
  include Pageable

  scope :order_by_position, -> { order(position: :asc, id: :desc) }
end

app/models/setting.rb
class Setting < ActiveRecord::Base
end

app/models/take.rb
class Take < ActiveRecord::Base
  extend FriendlyId
  include Searchable
  include Pageable
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :set_locale
  before_filter :fix_caching_problem
  before_filter :check_for_closed if ENV['CLOSED'] == 'true'
  before_action :load_global_resources

  helper_method :in_admin?

  # http://erlingur.is/post/68977749545/safari-7-blank-page-problem
  def fix_caching_problem
    headers['Last-Modified'] = Time.now.httpdate
  end

  def check_for_closed
    unless user_signed_in? || in_admin?
      redirect_to closed_url, status: 302
    end
  end

  def load_global_resources
    unless in_admin?
      @about_category = PageCategory.find_by_id(1)
      @svt_category = PageCategory.find_by_id(2)
      @projects = Project.published.order_by_position
      @settings = SiteSettings.new Setting.all
    end
  end

  def set_locale
    # A hacky way to set activeadmin to english but keep rest of site in swedish
    # todo: find a cleaner way to do this
    I18n.locale = in_admin? ? :en : I18n.default_locale
  end

  def in_admin?
    params[:controller].include?('admin/')
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def show
    @page = Page.friendly.find params[:id]

    respond_to do |format|
      format.html
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.published

    respond_to do |format|
      format.html
    end
  end

  def show
    @product = Product.friendly.find params[:id]

    respond_to do |format|
      format.html
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def show
    @project = Project.friendly.find params[:id]

    respond_to do |format|
      format.html
    end
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    q = params[:q]

    if q.present?
      @result =
        Project.search(q) +
        Page.search(q) +
        Take.search(q) +
        Product.search(q)
    end

    respond_to do |format|
      format.html
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  skip_before_filter :check_for_closed, only: :closed

  def start
  end

  def closed
    render layout: false
  end
end

app/controllers/takes_controller.rb
class TakesController < ApplicationController
  def index
    @takes = Take.published

    respond_to do |format|
      format.html
    end
  end

  def show
    @take = Take.friendly.find params[:id]

    respond_to do |format|
      format.html
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def translate_link
    "http://www.microsofttranslator.com/bv.aspx?from=&to=en&a=#{root_url}"
  end

  def markdown(content)
    markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, autolink: true)
    markdown.render(content).html_safe
  end

  def page_markdown(content, resource = nil)
    page_markdown = Redcarpet::Markdown.new PageMarkdown.new(resource: resource)
    page_markdown.render(content).html_safe
  end

  def tooltip_markdown(content, resource = nil)
    tooltip_markdown = Redcarpet::Markdown.new TooltipMarkdown.new(resource: resource)
    tooltip_markdown.render(content).html_safe
  end
end

app/views/admin/dashboard/_dashboard.slim
h2 Markdown cheet sheat

p Markdown’s syntax is intended for one purpose: to be used as a format for writing for the web.

hr

h3 Text formatting

h4 Emphasis
p
  code = "*asterisks*"

h4 Strong emphasis
p
  code = "**double asterisks**"

h4 Insert a link
p
  code = "[Example link](http://example.com)"

h4 Text color
p
  code = '<span style="color: #00ff00">some lime text</span>'

h4 Headlines
p
  code ## Headline 2
  br
  code ### Headline 3

h4 Unordered list
p
  code
    |
      * List item
      <br>
      * Another list item
      <br>
      * Yada yada

h4 Ordered list
p
  code
    |
      1. One
      <br>
      2. Two
      <br>
      3. Three

h4 New line
p When you do want to insert a <code>&lt;br&gt;</code> break tag using Markdown, you end a line with <b>two or more spaces</b>, then type return.

hr

h3 Images

h4 Insert a image with caption
p
  code = "[image:123]"

h4 Insert a image gallery of all images belonging to the project or page
p
  code = "[images]"

hr

h3 Video

h4 Insert a Vimeo video
p
  code = "[vimeo:2202918]"

h4 Insert a YouTube video
p
  code = "[youtube:HguL2bIri1Q]"

hr

h3 Attachments

h4 Insert an attachment
code = "[attachment:123]"

hr

h3 More

p
  |
    For more info, see <a href="http://daringfireball.net/projects/markdown/" target="_blank">John Gruber's original spec</a>

p
  |
    Always provide an <a href="http://en.wikipedia.org/wiki/Alt_attribute" target="_blank">alternative text for images</a>.

app/views/layouts/application.slim
doctype html
html.no-js
  head
    meta charset='utf-8'
    title = content_for?(:title) ? ("#{yield(:title)} / Mossutställningar").html_safe : 'Mossutställningar'
    meta name='viewport' content='width=device-width,initial-scale=1,maximum-scale=1'
    meta name='description' content="#{yield(:meta_description).present? ? yield(:meta_description) : 'Mossutställningar skapar förutsättningar för konstnärer att låta visionen gå före frågor om tid, plats och budget.'}"

    meta property='og:locale' content='sv_SE'
    meta property='og:type' content='website'
    meta property="og:title" content="#{content_for?(:title) ? ("#{yield(:title)} / Mossutställningar").html_safe : 'Mossutställningar'}"
    meta property="og:description" content="#{content_for?(:meta_description) ? yield(:meta_description) : 'Mossutställningar skapar förutsättningar för konstnärer att låta visionen gå före frågor om tid, plats och budget.'}"
    meta property='og:image' content="#{content_for?(:meta_image) ? yield(:meta_image) : asset_url('mossutstallningar.jpg')}"
    meta property='og:url' content="#{request.original_url}"
    meta property='og:site_name' content='Mossutställningar'

    - if content_for?(:meta)
      = yield :meta

    - if ENV['NO_INDEX'] == 'true'
      meta name='robots' content='noindex, nofollow'

    == stylesheet_link_tag 'application', media: nil
    == javascript_include_tag 'libs/modernizr'
    == csrf_meta_tags
  body class="#{content_for?(:body_class) ? " " + yield(:body_class) : nil}"
    = render 'shared/loader'

    main#main
      .dashboard
        .wrapper
          = render 'shared/header'
          = render 'shared/sitemap'
          = render 'shared/footer'
      .pages
        - unless current_page?(root_url)
          == yield

    - if ENV['SHOW_OVERLAY'] == 'true'
      .overlay

    - if ENV['SHOW_NAVIGATION_LINES'] == 'true'
      canvas#navigation-lines

    | <!--[if lt IE 9]>
    script src='//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js'
    | <![endif]-->
    | <!--[if gte IE 9]><!-->
    script src='//ajax.googleapis.com/ajax/libs/jquery/2.1.0/jquery.min.js'
    | <!--<![endif]-->

    script
      |
        (function(d){
            var f = d.getElementsByTagName('script')[0], p = d.createElement('script');
            p.async = true;
            p.src = '//assets.pinterest.com/js/pinit.js';
            f.parentNode.insertBefore(p, f);
        }(document));

    javascript:
      App = {
        options: {
          showNavigationLines: #{ENV['SHOW_NAVIGATION_LINES']},
          showGhost: #{ENV['SHOW_GHOST']},
          showOverlay: #{ENV['SHOW_OVERLAY']}
        }
      };

    == javascript_include_tag 'application'

    - if ENV['GOOGLE_ANALYTICS_ID'].present?
      script
        |
          (function(G,o,O,g,l){G.GoogleAnalyticsObject=O;G[O]||(G[O]=function(){
          (G[O].q=G[O].q||[]).push(arguments)});G[O].l=+new Date;g=
          o.createElement('script'),l=o.scripts[0];
          g.src='//www.google-analytics.com/analytics.js';
          l.parentNode.insertBefore(g,l)}(this,document,'ga'));
          ga('create','#{ENV['GOOGLE_ANALYTICS_ID']}');ga('send','pageview')

app/views/pageable/_show.slim
- content_for :title, resource.title
- if resource.body.present?
  - content_for :meta_description, truncate(resource.body, length: 150)
- if resource.featured_image.present?
  - content_for :meta_image, resource.featured_image.small
- unless resource.published
  - content_for :meta do
    meta name='robots' content='noindex, nofollow'

div class=["page page-#{type}"] id="page-id-#{resource.id}" tabindex='-1'
  = render 'shared/close'
  h1.page-title.dynamic-font-size = resource.title
  - if resource.body.present?
    .page-text.dynamic-font-size-children
      = page_markdown resource.body, resource
  footer.page-footer
    span.page-footer-share Dela sidan:
    a.button.share-facebook href="https://www.facebook.com/sharer.php?u=#{URI.escape(request.original_url)}&t=#{URI.escape(resource.title)}" target="_blank"
      i.fa.fa-facebook-square
      .span.button-text Dela på Facebook

app/views/pages/show.slim
- if @page.page_category.id == 1
  - content_for :body_class, 'page-type-about'
  - type = 'about'
- if @page.page_category.id == 2
  - content_for :body_class, 'page-type-svt'
  - type = 'svt'

= render 'pageable/show', resource: @page, type: type

app/views/products/index.slim
- content_for :title, 'Köp'

.page.page-product id='page-id-products' tabindex='-1'
  = render 'shared/close'
  h1.page-title.dynamic-font-size Köp
  .page-text.dynamic-font-size-children
    - if @products.present?
      ul.page-split-list.sitemap-category-list
        - @products.each do |item|
          li.sitemap-category-item
            = link_to fa_icon('chevron-right', text: item.title), item, class: 'internal sitemap-link page-index-link', data: { :'page-slug' => "page-id-#{item.id}" }

app/views/products/show.slim
= render 'pageable/show', resource: @product, type: 'product'

app/views/projects/show.slim
= render 'pageable/show', resource: @project, type: 'project'

app/views/search/index.slim
- content_for :title, "#{params[:q]} / Sök"

.page.page-search id='page-id-search'
  = render 'shared/close'
  h1.page-title.dynamic-font-size = %-Sökresultat för "#{params[:q]}"-
  .page-text.dynamic-font-size-children
    - if @result.present?
      ul.page-split-list.sitemap-category-list
        - @result.each do |item|
          li.sitemap-category-item
            = link_to fa_icon('chevron-right', text: item.title), item, class: 'internal sitemap-link page-index-link', data: { :'page-slug' => "page-id-#{item.id}" }
    - else
      p Inga träffar

app/views/shared/_close.slim
= link_to root_path, class: 'button close' do
  = fa_icon 'times'
  span.button-text Stäng

app/views/shared/_footer.slim
#encoding: utf-8

footer.footer.dynamic-font-size
  .contact-row
    = 'Mossutställningar'
  .contact-row
    = "Lilla Sällskapets väg 58, 127 61 Skärholmen, #{content_tag(:span, mail_to('info@mossutstallningar.com', 'info@mossutstallningar.com', class: 'footer-contact-link'), class: 'contact-row-email')}".html_safe
  - if user_signed_in?
    .additional-links
      = link_to 'Admin', admin_root_path, class: 'additional-link'

app/views/shared/_header.slim
#encoding: utf-8

header.header
  - if current_page?(root_url)
    h1.logotype-wrapper = render 'shared/logotype'
  - else
    .logotype-wrapper = render 'shared/logotype'

  nav.header-nav.dynamic-font-size
    ul.header-nav-list
      li.header-nav-list-item.header-nav-list-item-products
        = link_to 'Köp', products_path, class: "internal header-nav-link navigation-lines-link#{@settings.buy_text.present? ? ' tooltip-trigger' : '' }", data: { color: '#f0f', :'page-slug' => 'page-id-products', 'tooltip-relative' => true }
        - if @settings.buy_text.present?
          .tooltip = markdown(@settings.buy_text)
      li.header-nav-list-item.header-nav-list-item-giveaways
        = link_to 'Bortskänkes', takes_path, class: "internal header-nav-link navigation-lines-link#{@settings.giveaways_text.present? ? ' tooltip-trigger' : '' }", data: { color: '#00f', :'page-slug' => 'page-id-takes', 'tooltip-relative' => true }
        - if @settings.giveaways_text.present?
          .tooltip = markdown(@settings.giveaways_text)
      li.header-nav-list-item.header-nav-list-item-translate
        = link_to 'Translate', translate_link, class: "header-nav-link navigation-lines-link#{@settings.translate_text.present? ? ' tooltip-trigger' : '' }", data: { color: '#ff0', 'tooltip-relative' => true }
        - if @settings.translate_text.present?
          .tooltip = markdown(@settings.translate_text)
      li.header-nav-list-item.header-nav-list-item-search
        .search class=[params[:q].present? ? 'search-open' : 'search-closed']
          button class="search-opener header-nav-link navigation-lines-link#{@settings.search_text.present? ? ' tooltip-trigger' : '' }" data-color='#000' data-tooltip-relative='true' Sök
          - if @settings.search_text.present?
            .tooltip = markdown(@settings.search_text)
          = form_tag search_path, method: 'get', class: 'search-form internal-form', data: { :'page-slug' => 'page-id-search' } do
            = label_tag :q, 'Sök:', class: 'search-label'
            = search_field_tag :q, params[:q], placeholder: 'Sök', class: 'search-query'
            = button_tag fa_icon('chevron-right'), class: 'search-submit'

app/views/shared/_loader.slim
= image_tag asset_path('loader.png'), class: 'loader'

app/views/shared/_logotype.slim
#encoding: utf-8

= link_to 'Mossutställningar', root_path, class: "page-reset logotype dynamic-font-size#{@settings.logo_text.present? ? ' tooltip-trigger' : '' }", data: { 'tooltip-relative' => true }
- if @settings.logo_text.present?
  .tooltip = markdown(@settings.logo_text)

app/views/shared/_sitemap.slim
ul.sitemap.dynamic-font-size
  - if @about_category.present?
    li.sitemap-category.sitemap-category-about
      span.sitemap-category-headline = @about_category.name
      = render 'shared/sitemap_list', items: @about_category.pages.published.order_by_position, color: '#fc1997'
  - if @svt_category.present?
    li.sitemap-category.sitemap-category-svt
      span.sitemap-category-headline = @svt_category.name
      = render 'shared/sitemap_list', items: @svt_category.pages.published.order_by_position, color: '#8a1fda'
  - if @projects.present?
    li.sitemap-category.sitemap-category-project
      span.sitemap-category-headline = 'Konst'
      = render 'shared/sitemap_list', items: @projects, color: '#126afb'

app/views/shared/_sitemap_list.slim
ul.sitemap-category-list
  - items.each do |item|
    li.sitemap-category-item
      = link_to fa_icon('chevron-right', text: item.title), item, class: "internal navigation-lines-link sitemap-link#{((item.kind_of?(Project) || item.kind_of?(Page)) && item.description.present?)? ' tooltip-trigger' : ''}", data: { :'page-slug' => "page-id-#{item.id}", color: color }
      - if (item.kind_of?(Project) || item.kind_of?(Page)) && item.description.present?
        div.tooltip = tooltip_markdown item.description

app/views/static_pages/closed.slim
doctype html
html.no-js
  head
    meta charset='utf-8'
    title = 'Mossutställningar'
    meta name='viewport' content='width=device-width,initial-scale=1,maximum-scale=1'
    meta name='description' content="#{yield(:meta_description).present? ? yield(:meta_description) : 'Mossutställningar skapar förutsättningar för konstnärer att låta visionen gå före frågor om tid, plats och budget.'}"

    meta property='og:locale' content='sv_SE'
    meta property='og:type' content='website'
    meta property="og:title" content="#{content_for?(:title) ? ("#{yield(:title)} / Mossutställningar").html_safe : 'Mossutställningar'}"
    meta property="og:description" content="#{content_for?(:meta_description) ? yield(:meta_description) : 'Mossutställningar skapar förutsättningar för konstnärer att låta visionen gå före frågor om tid, plats och budget.'}"
    meta property='og:image' content="#{content_for?(:meta_image) ? yield(:meta_image) : asset_url('mossutstallningar.jpg')}"
    meta property='og:url' content="#{request.original_url}"
    meta property='og:site_name' content='Mossutställningar'

    meta name='robots' content='noindex, nofollow'

    == stylesheet_link_tag 'application', media: nil
    == javascript_include_tag 'libs/modernizr'
    == csrf_meta_tags
  body
    .wrapper
      .page-reset.logotype.dynamic-font-size Mossutställningar kommer snart!

app/views/static_pages/svt.slim
- if @svt_category.present?
  - content_for :title, @svt_category.name

  .page.page-search id='page-id-svt-index'
    = render 'shared/close'
    h1.page-title.dynamic-font-size = @svt_category.name
    .page-text.dynamic-font-size-children
      ul.page-split-list.sitemap-category-list
        - @svt_category.pages.published.each do |item|
          li.sitemap-category-item
            = link_to fa_icon('chevron-right', text: item.title), item, class: 'internal sitemap-link page-index-link', data: { :'page-slug' => "page-id-#{item.id}" }

app/views/takes/index.slim
- content_for :title, 'Bortskänkes'

.page.page-take id='page-id-takes' tabindex='-1'
  = render 'shared/close'
  h1.page-title.dynamic-font-size Bortskänkes
  .page-text.dynamic-font-size-children
    - if @takes.present?
      ul.page-split-list.sitemap-category-list
        - @takes.each do |item|
          li.sitemap-category-item
            = link_to fa_icon('chevron-right', text: item.title), item, class: 'internal sitemap-link page-index-link', data: { :'page-slug' => "page-id-#{item.id}" }

app/views/takes/show.slim
= render 'pageable/show', resource: @take, type: 'take'